Convert the Action into TypeScript
DeterminateSystems/update-flake-lock pull request #101
Opened 2024-04-26 14:55 UTC by lucperkins

- Add initial JS setup
- Update Nix shell and add envrc
- Construct Nix command
- Finish initial rework into TS

2024-05-06 20:07 UTC, grahamc requested changes
Looking real close, but the nit about `cd`. I'll send a fixup.

2024-05-06 20:07 UTC, grahamc commented on src/index.ts
> +    }
You can't exec `cd` like this, because the parent process's pwd isn't impacted.

```suggestion
```

2024-05-06 20:07 UTC, grahamc commented on src/index.ts
> +    const exitCode = await actionsExec.exec("nix", nixCommandArgs);
```suggestion
    actionsCore.debug(`running nix command:\n${fullNixCommand}`);

    const exitCode = await actionsExec.exec("nix", nixCommandArgs, { cwd: this.pathToFlakeDir });
```

is probably closer to what we need.

2024-05-07 14:23 UTC, grahamc commented on action.yml
> +      uses: DeterminateSystems/update-flake-lock/.github/actions/typescript@detsys-ts
```suggestion
      uses: DeterminateSystems/update-flake-lock/.github/actions/typescript@detsys-ts
```

Dicey, we should pin this to an exact hash.

2024-05-07 14:53 UTC, cole-h commented on action.yml
>      - name: Run update-flake-lock.sh
This looks incorrect.

2024-05-07 14:56 UTC, cole-h commented on action.yml
> +      uses: DeterminateSystems/update-flake-lock/.github/actions/typescript@detsys-ts
Hm, why can't we rely on the repository-local file path? It should be possible to use `./.github/actions/typescript/action.yml` here. (We had to use `$GITHUB_ACTION_PATH` before because we were executing a file from this action's repository, but I think `uses` is evaluated in the context of the action itself before anything is actually run?)

2024-05-08 03:04 UTC, grahamc commented on action.yml
> +      uses: DeterminateSystems/update-flake-lock/.github/actions/typescript@detsys-ts
I stopped being silly and remembered I could just run `node ./.../index.js`.

2024-05-09 17:17 UTC, cole-h requested changes
Doesn't seem to work as-is for me; no PR gets created.

https://github.com/cole-h/update-flake-lock-test/actions/runs/9020862190/job/24786935346 was run from the HEAD (at the time) of this branch -- notice how no PR was created, as evidenced by the lack of a number in the "echo" step:

![image](https://github.com/DeterminateSystems/update-flake-lock/assets/28582702/52a6ba45-40e4-45ed-95f4-3011b62a4a92)

https://github.com/cole-h/update-flake-lock-test/actions/runs/9020902721/job/24787061455 was run off of `main`, a PR was created, and the echo step has a PR number:

![image](https://github.com/DeterminateSystems/update-flake-lock/assets/28582702/e229387a-8370-4ba6-b3da-b93f09794c74)

2024-05-09 19:40 UTC, cole-h commented on action.yml
> +      run: node "$GITHUB_ACTION_PATH/dist/index.js"
nit: can we move this above this huge block of `env`s?

2024-05-09 19:40 UTC, cole-h commented on src/index.ts
> +    // nix flake lock --commit-lock-file --commit-lockfile-summary "updated flake.lock"
nit:

```suggestion
    // nix flake update --commit-lock-file --commit-lockfile-summary "updated flake.lock"
```

2024-05-09 19:41 UTC, cole-h commented on src/index.ts
> +    // nix ${maybe nix options} flake lock ${maybe --update-input flags} --commit-lock-file --commit-lockfile-summary ${commit message}
```suggestion
    // nix ${maybe nix options} flake ${update" or "lock"} ${maybe --update-input flags} --commit-lock-file --commit-lockfile-summary ${commit message}
```

2024-05-09 19:49 UTC, cole-h approved these changes
LGTM, but we should b e prepared to receive issues over the next while about this breaking things that were not tested very deeply.

2024-05-09 19:50 UTC, grahamc commented
Agreed.

2024-05-09 19:50 UTC, merged